version: "3.9"

services:
  db:
    image: postgres:16
    container_name: dk-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: dk-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  db_data:
  es_data:
